server_ip: 127.0.0.1
server_port: 3434
cache_age: 8460000
session_timeout: 300
program_name: Didi SPA
author: Mukoni Software
description: Didi Framework Single Page Application
keywords: didingwe,didi,mukoni,Mukoni Software,spa
viewport: width=device-width, initial-scale=1
charset: iso-8859-1
root_path: ..
didi_root: $root_path/didingwe
didi_path: $didi_root/vocab
didi_web: $didi_root/web
image_path: $web_path/images
didi_themes: $didi_root/themes
themes: $didi_themes/basic
program_path: $root_path/vocab
site_config: $program_path/.site-config.yml
image_url: /images
favicon: 
  type: image/png
  href: /didi/images/mukoni-favicon.png

title: $program_name

search_paths:
  - $didi_path
  - $themes
  - $program_path

site_layout: /spa

spa:
  page: $site_layout
  template: $didi_web/spa.html
  content: /home
  public: {}
  auth: {}

log:
  dir: $root_path/log
  path: $root_path/log/$program_name.log
  level: 4
  max_response: 127
upload_dir: $root_path/uploads
start_page: /home
head_tag: 
  meta: { name: $name, content: $value}
  favicon: { tag: link, rel: icon }
  css: { tag: link, rel: stylesheet, type: text/css, media: screen, href: $value}
  script: { src: $value, alias: scripts, text: "" }
  title: { text: $value }

meta:
  - { http-equiv: Content-Type, content: "text/html; charset=$charset" }
  - { http-equiv: X-UA-Compatible, content: IE=edge }
  - keywords: $keywords
  - author: $author
  - description: $description
  - viewport: $viewport
  - application-name: $program_name
css:
  - /didi/css/font-awesome/css/font-awesome.min.css
  - /didi/css/didi.css

script:
  - /didi/js/jquery-3.2.1.min.js
  - /didi/js/jquery-ui-1.12.1.min.js
  - /didi/js/enquire.min.js
  - /didi/js/didi.prototype-ext.js
  - /didi/js/didi.util.js
  - /didi/js/didi.jquery.js
  - /didi/js/didi.render.js
   
  
modules:
  - db: mysql
  - db2: mysql
  - auth
  - validator
  - curl
  - collection
  - emailer
  - sms
  - document

aliases:
  /^sql_(.+)$/: db.$1
  sql: db.sql
  sql_list: db.read_column

mysql:
  path: mysql/db.php
  host: localhost
  port: 3306
  database: didi
  user: didi
  password: mukoni
  connectionLimit: 1
  multipleStatements: no


collections:
  default: collection
  auth: [user,partner,user_group,user_group_member]
  session: [session,audit,token]
  billing: [rate,payment,credit,transaction,country_rate]
  document: [document]
  trigger: [trigger,hook,promo_entry]
use_triggers: no


registrar: Mukoni Software
registrar_role: admin

registrant_partner: Mukoni Software
registrant_role: registrant

email_new_registration: yes

email_otp: yes
sms_otp: yes
self_activation_validity: 48 hour

request_method: post
smtp_host: smtp.example.com
smtp_user: email@example.com
smtp_password: mypassword
sms.send:
  protocol: http
  port: 80
  host: www.qmessenger.co.za
  user: minime
  password: mypassword
  cellphone: $cellphone
  path: web2sms/submit?uid=$user&pw=$password&sms=$message&da=$msisdn
emailer.send:
#  SMTPDebug: 2
  isSMTP: true
  SMTPSecure: false
  SMTPAuth: true
  port: 25
  isHTML: true

paygate_id: 1231231
paygate_secret: secret
paygate_url: https://secure.paygate.co.za/payweb3/initiate.trans
