site_config: .site-config.yml
server_ip: 127.0.0.1
server_port: 3434
cache_age: 8460000
program_name: Didi SPA
brand_name: $program_name
brand_path: $brand_name
root_path: ..
didi_root: $root_path/didi
didi_path: $didi_root/vocab
didi_web: $didi_root/web
image_path: $web_path/images
themes: [$didi_path/themes/didi]
image_url: /images
search_paths:
  - $didi_path
  - $themes
  - vocab
  - $brand_path
spa:
  default:
  page: /index
  template: /spa.html
  path: /home
  content: $path
  public: {}
  auth: {}
log:
  path: $root_path/log/$brand_name.log
  level: 4
  max_response: 127
upload_dir: $root_path/uploads
start_page: /home
css:
  - /didi/css/font-awesome/css/font-awesome.min.css
  - /didi/css/didi.css
scripts:
  - /didi/js/jquery-3.2.1.min.js
  - /didi/js/jquery-ui-1.12.1.min.js
  - /didi/js/enquire.min.js
  - /didi/js/mukoni.jquery.js
  - /didi/js/mkn.js
  - /didi/js/mkn.render.js
  - /didi/js/page.js
modules:
  - auth
  - collection
  - emailer
  - sms
  - document
  #- db: didi-mysql

didi-mysql:
  host: localhost
  port: 3306
  database: didi
  user: didi
  password: mukoni
  connectionLimit: 1
  multipleStatements: no


collections:
  default: collection
  auth: [user,partner,user_group,user_group_member]
  session: [session,audit,token]
  billing: [rate,payment,credit,transaction,country_rate]
  document: [document]
  trigger: [trigger,hook,promo_entry]
use_triggers: no


registrar: Mukoni Software
registrar_role: admin

registrant_partner: Mukoni Software
registrant_role: registrant

email_new_registration: yes

email_otp: yes
sms_otp: yes
self_activation_validity: 48 hour

request_method: post
smtp_host: smtp.example.com
smtp_user: email@example.com
smtp_password: mypassword
sms.send:
  protocol: http
  port: 80
  host: www.qmessenger.co.za
  user: minime
  password: mypassword
  cellphone: $cellphone
  path: web2sms/submit?uid=$user&pw=$password&sms=$message&da=$msisdn
emailer.send:
#  SMTPDebug: 2
  isSMTP: true
  SMTPSecure: false
  SMTPAuth: true
  port: 25
  isHTML: true

paygate_id: 10011072130
paygate_secret: secret
paygate_url: https://secure.paygate.co.za/payweb3/initiate.trans
