site_config: .site-config.yml
server_ip: 127.0.0.1
server_port: 3434
cache_age: 8460000
resource_dir: ./web
program_name: Didi SPA
brand_name: $program_name
brand_path: branding/$brand_name
didi_path: ../didi/
search_paths: [$didi_path,.,$brand_path]
image_path: /images
spa:
  default:
    page: /index
    template: /spa.html
    path: /home
    content: $path
  public: {}
  auth: {}
logging:
  path: ../log/$brand_name.log
  level: trace
  max_response: 127
upload_dir: ../uploads
start_page: /home
css:
  - /didi.css
script:
  - /jquery-3.2.1.min.js
  - /jquery-ui-1.12.1.min.js
  - /enquire.min.js
  - /mukoni.jquery.js
  - /mkn.js
  - /mkn.render.js
  - /page.js
modules:
  - auth
  - collection
  - emailer
  - sms
  - document

collections:
  default: collection
  auth: [user,partner,user_group,user_group_member]
  session: [session,audit,token]
  billing: [rate,payment,credit,transaction,country_rate]
  document: [document]
  trigger: [trigger,hook,promo_entry]
use_triggers: no


registrar: Mukoni Software
registrar_role: admin

registrant_partner: Mukoni Software
registrant_role: registrant

email_new_registration: yes

email_otp: yes
sms_otp: yes
self_activation_validity: 48 hour

request_method: post
smtp_host: smtp.example.com
smtp_user: email@example.com
smtp_password: mypassword
sms.send:
  protocol: http
  port: 80
  host: www.qmessenger.co.za
  user: minime
  password: mypassword
  cellphone: $cellphone
  path: web2sms/submit?uid=$user&pw=$password&sms=$message&da=$msisdn
emailer.send:
  smtp:
    host: smtp.example.com
    user: me@example.com
    password: mypassword

paygate_id: 10011072130
paygate_secret: secret
paygate_url: https://secure.paygate.co.za/payweb3/initiate.trans
